#  Metirc
- 모델 성능 평가지표
- 실제값과 모델에 의해 예측된 값을 비교하여 모델의 성능을 측정
- 모델 평가 목적
    - 최적의 모델을 찾기 위해

# regression model 의 성능 지표
- MSE
- RMSE
- MAE
- MAPE
- SMAPE
- R2 Score

# Classification 의 성능 지표
- Accuracy
- Precision-Recall
- ROC-AUC
- Log-loss

- 회귀 문제 성능측정
    - 실제값과 예측값의 차이를 측정

# 회귀 문제 성능측정

## 당뇨병 진행 예측
- 당뇨병 진행도를 예측하는 데이터셋

In [1]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
diabetes.data, diabetes.target

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
   

In [4]:
# data 의 총 갯수는 442개, 특징은 10개 
diabetes.data.shape

(442, 10)

In [5]:
diabetes.target.shape

(442,)

In [6]:
data, target  = diabetes.data, diabetes.target

In [9]:
# diabetes 데이터에 대한 설명
# documnets 확인
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [11]:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have bee

In [12]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [16]:
diabetes.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613])

In [19]:
# 당뇨병 진행도를 예측하는 DATASETS
target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [20]:
# w_0(=b) + w_1*x_1 +w_2 *x_2 + w_3 * x_3 + ... + w_10 * x_10 
# b + W^T X

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
model_linear = LinearRegression()

In [32]:
model_linear.fit(data, target)

LinearRegression()

In [35]:
y_predict = model_linear.predict(data)

## Linear Regression 모델을 이용한 학습 및 예측

In [37]:
y_predict #?

array([206.11667725,  68.07103297, 176.88279035, 166.91445843,
       128.46225834, 106.35191443,  73.89134662, 118.85423042,
       158.80889721, 213.58462442,  97.07481511,  95.10108423,
       115.06915952, 164.67656842, 103.07814257, 177.17487964,
       211.7570922 , 182.84134823, 148.00326937, 124.01754066,
       120.33362197,  85.80068961, 113.1134589 , 252.45225837,
       165.48779206, 147.71997564,  97.12871541, 179.09358468,
       129.05345958, 184.7811403 , 158.71516713,  69.47575778,
       261.50385365, 112.82234716,  78.37318279,  87.66360785,
       207.92114668, 157.87641942, 240.84708073, 136.93257456,
       153.48044608,  74.15426666, 145.62742227,  77.82978811,
       221.07832768, 125.21957584, 142.6029986 , 109.49562511,
        73.14181818, 189.87117754, 157.9350104 , 169.55699526,
       134.1851441 , 157.72539008, 139.11104979,  72.73116856,
       207.82676612,  80.11171342, 104.08335958, 134.57871054,
       114.23552012, 180.67628279,  61.12935368,  98.72

## 회귀 평가 지표


### MSE(Mean Squared Error)
$$
MSE = \frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}
$$
- 실제값과 예측값의 차이를 제곱해서 평균화
- 이상치에 민감
- 직관적이지 못하다.
- 손실함수로 주로 사용한다. -> 미분이 쉬우니깐


In [39]:
from sklearn.metrics import mean_squared_error
# https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics
mse = mean_squared_error(y_predict, target)
mse

2859.69634758675

### RMSE(Root Mean Squared Error)
$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$
- MSE에 루트
- 이상치 민감


In [40]:
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
mse = mean_squared_error(y_predict, target, squared=False)
mse

C:\Users\ohminy\anaconda3\envs\week4\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


53.47612876402657

In [42]:
from sklearn.metrics import root_mean_squared_error # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html
mse = root_mean_squared_error(y_predict, target)
mse

53.47612876402657

### MAE(Mean Absolute Error)
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$
- 실제값과 예측값의 차이를 절대값으로 변환해서 평균화
- 직관적이다.

In [45]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_predict, target)

43.27745202531506

### MAPE (Mean Absolute Percentage Error)
$$
MAPE = \frac{100}{n}{\sum_{i=1}^{n}\frac{|y_i-\hat{y}_i|}{y_i}}
$$
- 실제값에 대한 절대오차 비율의 평균을 퍼센트로 표현

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error


### SMAPE (Symmetric Mean Absolute Percentage Error)
$$
SMAPE = \frac{100}{n}{\sum_{i=1}^{n}\frac{|y_i-\hat{y_i}|}{{|y_i|}+|\hat{y_i}|}}
$$
- 기존 mape의 단점을 보완한것
- MAPE와 다른점은 각 실제값과 예측값을 절대값으로 변경후 핪으로 나눈다.
- MAPE와 다르게 실제값에 0이 존재해도 계산이 가능하다.
- 실제값보다 예측값이 크거나 작을수도있다.
- 예측값이 실제값보다 작을때, 분모가 작아지기 때문에 오차가 커지게 된다. (과소추정에 대한 패널티가 줄수가 있다.)


In [48]:
import numpy as np

In [49]:
def smape(true,pred):
    error =  np.abs(true - pred) / (np.abs(true) + np.abs(pred))
    return np.mean(error)
smape(y_predict, target)

0.1570051649606364

# $R^2$Score

- 회귀 분석에서 모델의 적합도를 평가하는 중요한 지표
- 제 관측값의 분산 대비 예측값의 분산을 나타내며, 모델이 데이터를 얼마나 잘 설명하는지를 수치적으로 보여준다
- $R^2$ 의 값은 $0$부터 $1$까지 범위를 가지며, $1$에 가까울수록 모델이 데이터를 완벽하게 설명한다는 의미입니다.
- $R^2 = 1$은 모델이 데이터를 완벽하게 설명하고 있음을 의미합니다. 즉, 모든 관측치가 회귀선에 위치합니다.
- $R^2 = 0$ 은 사용된 독립변수가 종속변수를 설명하는 데 전혀 도움이 되지 않는다는 것을 나타냅니다.

$$
R^2 = \frac{SSR}{SST} = 1 - \frac{SSE}{SST}
$$

- $SST$ (Sum of Squares Total
    - 관측값과 평균값의 차이를 제곱하여 더한 것으로, 데이터의 총 변동을 나타 낸다.
- $SSE$ (Sum of Squared Error)
    - 관측값과 예측값의 차이(잔차)를 제곱하여 더한 것으로, 모델이 설명하지 못하는 변동을 나타낸다.
- $SSR$  (Sum of Squares due to Regression)은 예측값과 평균값의 차이를 제곱하여 더한 것으로, 모델이 설명하는 변동의 크기를 나타낸다.

### 정리

$R^2$ 값이 높을수록 모델이 데이터를 더 잘 설명하고 있다고 해석할 수 있으며, 이는 모델의 예측 정확도가 높다는 것을 의미한다
- 0.4 이상이면 대체적으로 유의미하다고 판단한다.

In [50]:
from sklearn.metrics import r2_score

In [53]:
r2_score?

Signature:
r2_score(
    y_true,
    y_pred,
    *,
    sample_weight=None,
    multioutput='uniform_average',
    force_finite=True,
)
Docstring:
:math:`R^2` (coefficient of determination) regression score function.

Best possible score is 1.0 and it can be negative (because the
model can be arbitrarily worse). In the general case when the true y is
non-constant, a constant model that always predicts the average y
disregarding the input features would get a :math:`R^2` score of 0.0.

In the particular case when ``y_true`` is constant, the :math:`R^2` score
is not finite: it is either ``NaN`` (perfect predictions) or ``-Inf``
(imperfect predictions). To prevent such non-finite numbers to pollute
higher-level experiments such as a grid search cross-validation, by default
these cases are replaced with 1.0 (perfect predictions) or 0.0 (imperfect
predictions) respectively. You can set ``force_finite`` to ``False`` to
prevent this fix from happening.

Note: when the prediction residuals hav

In [52]:
r2_score(target, y_predict
# 모델이 데이터셋에 대해 설명력을 갖고 있다. 

0.5177484222203499

In [ ]:
# https://dacon.io/forum/405791
# https://docs.h2o.ai/driverless-ai/korean-latest/docs/userguide/ko/scorers.html
# https://pseudo-lab.github.io/Tutorial-Book/chapters/time-series/Ch1-Time-Series.html