In [1]:
# 1. numpy 버전
import numpy as np
np.__version__

'1.26.4'

In [ ]:
# 2. 크기 10, 1차원, 원소 0 
# 2-1
a = np.array([0,0,0,0,0,0,0,0,0,0])
print(a)
print(a.shape)

In [ ]:
# 2-2 
b = np.zeros(10)
print(b)
print(b.shape)

In [ ]:
print(type(a))
print(type(b))

In [ ]:
c = np.zeros_like(b)

In [ ]:
print(type(c))

In [ ]:
d = np.full(10, 0)

In [ ]:
print(type(d))

In [ ]:
# 11.3
n_arr = np.arange(1,11)

In [ ]:
n_arr.dtype

In [ ]:
n_arr.itemsize # element의 byte 크기, 1byte 는 8bit 

In [ ]:
n_arr.size # element의 갯수

In [ ]:
n_arr.size * n_arr.itemsize # 크기 40 byte

In [ ]:
# 11.3-2 dtype 변경
n_arr = np.arange(1,11).astype("int64")

In [ ]:
n_arr.dtype

In [ ]:
n_arr.size * n_arr.itemsize 

In [ ]:
import sys

In [ ]:
sys.a.min()a.min()(1)

In [ ]:
# 11.4 1부터 10까지 
a = np.arange(1,11)
print(a)

In [ ]:
a[::-1] #[start, end, step]

In [ ]:
np.arange(10, 0, -1)

In [ ]:
b = a[::-1].copy()

In [ ]:
b.reshape(2,5)

In [ ]:
c = b.reshape(2,5).copy()

In [ ]:
c.reshape(5,2)

In [ ]:
# 1~16 -> 4x4 배열 
np.arange(1,17).reshape(4,4)

In [ ]:
# np.arange?

In [ ]:
# 참고 
# 난수 생성 알고리즘 -> seed 를 고정하여 난수생성 알고리즘을 실행하면 -> 항상 같은 난수가 생성된다.
np.random.seed(1234)

In [ ]:
a = np.random.random(10)

In [ ]:
a

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
a.mean()

In [ ]:
n = int(input("n : "))
arr_1 = np.full((n,n),0)
for i in range(n):
    for j in range(n):
        if (i+j)%2 == 0:
            arr_1[i,j] = 1
print(arr_1)

In [ ]:
arr_1 = np.full((4,4,),0)
arr_1

In [ ]:
arr_1[0,0] = 1

In [ ]:
arr_1

In [ ]:
n = int(input("n : "))
arr_1 = np.full((n,n),0)
for i in range(n):
    arr_1[i,i] = i+1
print(arr_1)

In [ ]:
n = int(input("n : "))
a = np.full((n,n),1)
b = a.copy()
b[1:-1, 1:-1] =0
print(a)
print(b)

In [ ]:
n = int(input("n : "))
a = np.full((n,n),1)
b = a.copy()
# b[[0,-1], :] = 0
# b[:, [0,-1]] = 0
b[[0,-1], :] = b[:, [0,-1]] = 0
print(b)

In [ ]:
a = np.arange(0,81,10)
b = np.arange(0,21,20)

In [ ]:
bool_arr = np.full(a.shape, True)
for idx, i in enumerate(a):
    if i not in b:
        bool_arr[idx] = False
print(bool_arr)

In [ ]:
bool_arr = np.full(a.shape, False)
for idx, i in enumerate(a):
    if i in b:
        bool_arr[idx] = True
print(bool_arr)

In [ ]:
from collections import Counter
arr_1 = np.array([[80, 120, 40], [60, 80, 120], [40, 40, 40]])
Counter(arr_1.flatten())

In [ ]:
dic_count = dict()
for j in arr_1:
    for i in j:
        if i in dic_count:
            dic_count[i] += 1
        else:
            dic_count[i] = 1

In [ ]:
dic_count

In [ ]:
dic_count = dict()
arr_2 = arr_1.flatten()
for i in arr_2:
    if i in dic_count:
        dic_count[i] += 1
    else:
        dic_count[i] = 1

In [ ]:
dic_count

In [ ]:
# 13 번
a = np.arange(0,81,10)
b = np.arange(0,21,20)

In [ ]:
c = np.empty(0) # 초기화

In [ ]:
for i in a:
    if i not in b: # 처음에는 not in 을 생각 하기가 어렵다. 
        c = np.append(c,i)

In [ ]:
np.setdiff1d(a, b)

In [165]:
# np.setdiff1d?

In [178]:
n = 11
arr_1 = np.eye(n) + np.eye(n)[::-1]
if n % 2 == 1:
    arr_1[int(n/2),int(n/2)] = 1
arr_1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [179]:
n = 11
arr_1 = np.eye(n) + np.eye(n)[::-1]
arr_1[arr_1>1] = 1
print(arr_1)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [2]:
# 15번

In [3]:
arr_1 = np.full((10,10), 0)

In [5]:
arr_1[1,1] = 1

In [8]:
arr_1[0,0] = 1

In [ ]:
arr_1[0,0] = 1

In [10]:
arr_1[1,0] = 1

In [14]:
arr_1[2,0] = arr_1[2,1] = arr_1[2,2] = 1

In [15]:
arr_1

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
# 방법1
n = 10
arr_1 = np.full((n,n), 0)
for i in range(n):
    for j in range(n):
        if i >= j:
            arr_1[i,j] = 1
print(arr_1)

[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
# 방법2(몰라도됨)
np.tril?

In [21]:
n = 10
np.tril(np.full((n,n), 1))

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [17]:
arr_1.sum()

55

In [23]:
arr_1.shape

(10, 10)

In [25]:
arr_1.sum(axis = 0)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [26]:
arr_1.sum(axis = 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr_1 = np.tril(np.full((n,n-3,n-5), 1))

In [30]:
arr_1.shape

(10, 7, 5)

In [31]:
arr_1.sum(axis = 1)

array([[7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3],
       [7, 6, 5, 4, 3]])

In [32]:
arr_1.sum(axis = 0)

array([[10,  0,  0,  0,  0],
       [10, 10,  0,  0,  0],
       [10, 10, 10,  0,  0],
       [10, 10, 10, 10,  0],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [33]:
arr_1.sum(axis = 2)

array([[1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5],
       [1, 2, 3, 4, 5, 5, 5]])

In [35]:
arr_1 = np.array([
    [0,1,2],
    [3,4,5],
    [0,2,4],
    [6,8,10]])

In [40]:
arr_1_1 = np.concatenate([arr_1[0], arr_1[2]])

In [41]:
arr_1_2 = np.concatenate([arr_1[1], arr_1[3]])

In [43]:
np.concatenate([arr_1_1, arr_1_2]).reshape(2,6)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10]])

In [44]:
# 17 번 
n = 5
arr_1 = np.ones((n,n))
arr_1[0, :] = arr_1[-1, :] = arr_1[:, 0] = arr_1[:, -1] =0
arr_1[2,2] = 2
print(arr_1)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 2. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
arr_1[1:-1,1:-1]

array([[1., 1., 1.],
       [1., 2., 1.],
       [1., 1., 1.]])

In [46]:
arr_1[:3,:3]

array([[0., 0., 0.],
       [0., 1., 1.],
       [0., 1., 2.]])

In [48]:
arr_1[:3,1:4]

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 2., 1.]])

In [49]:
arr_1[1:4,2:]

array([[1., 1., 0.],
       [2., 1., 0.],
       [1., 1., 0.]])

In [50]:
arr_1[2, :]

array([0., 1., 2., 1., 0.])

In [51]:
arr_1[:, 2]

array([0., 1., 2., 1., 0.])